# Generated by Django 5.1.15 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprofile',
            name='full_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='nim_nip',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
